function [fitresult, gof] = A_both(time, meanC_1, meanC_2, meanC_3, meanC_4, meanC_5, meanC_6, meanC_7)
%CREATEFITS1(TIME,MEANC_1,MEANC_2,MEANC_3,MEANC_4,MEANC_5,MEANC_6,MEANC_7)
%  Create fits.
%
%  Data for 'C=0' fit:
%      X Input : time
%      Y Output: meanC_1
%  Data for 'C=0.0625' fit:
%      X Input : time
%      Y Output: meanC_2
%  Data for 'C=0.125' fit:
%      X Input : time
%      Y Output: meanC_3
%  Data for 'C=0.25' fit:
%      X Input : time
%      Y Output: meanC_4
%  Data for 'C=0.5' fit:
%      X Input : time
%      Y Output: meanC_5
%  Data for 'C=1' fit:
%      X Input : time
%      Y Output: meanC_6
%  Data for 'C=2' fit:
%      X Input : time
%      Y Output: meanC_7
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Oct-2018 03:37:35

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 7, 1 );
gof = struct( 'sse', cell( 7, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'C=0'.
[xData, yData] = prepareCurveData( time, meanC_1 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.648198406466157 0.9 0.4 0.8422 0.2 6];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0' );
plot( fitresult{1}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_1
grid on

%% Fit: 'C=0.0625'.
[xData, yData] = prepareCurveData( time, meanC_2 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.347879194327261 0.446026648055103 0.157613081677548 0.0542394844411296 0.177107533789109 8];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.0625' );
plot( fitresult{2}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_2
grid on

%% Fit: 'C=0.125'.
[xData, yData] = prepareCurveData( time, meanC_3 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.330828995203305 0.8984861378343 0 0.118155198446711 0.988417928784981 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.125' );
plot( fitresult{3}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_3
grid on

%% Fit: 'C=0.25'.
[xData, yData] = prepareCurveData( time, meanC_4 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.05 0.5 0.05 0.9 0.2 20];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.25' );
plot( fitresult{4}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_4
grid on

%% Fit: 'C=0.5'.
[xData, yData] = prepareCurveData( time, meanC_5 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.763957078491957 0.818204038907671 0.655477890177557 0.100221540195492 0.178116953886766 5];

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.5' );
h = plot( fitresult{5}, xData, yData );
legend( h, 'meanC_5 vs. time', 'C=0.5', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel meanC_5
grid on

%% Fit: 'C=1'.
[xData, yData] = prepareCurveData( time, meanC_6 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', 1 );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.06 0.02 0.03 1 0.02 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=1' );
h = plot( fitresult{6}, xData, yData, excludedPoints );
legend( h, 'meanC_6 vs. time', 'Excluded meanC_6 vs. time', 'C=1', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel meanC_6
grid on

%% Fit: 'C=2'.
[xData, yData] = prepareCurveData( time, meanC_7 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.015 0.01 0.0015 1 0.01 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{7}, gof(7)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=2' );
plot( fitresult{7}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_7
grid on


