function [fitresult, gof] = A_nal(time, meanC_1, meanC_2, meanC_3, meanC_4, meanC_5, meanC_6, meanC_7)
%CREATEFITS1(TIME,MEANC_1,MEANC_2,MEANC_3,MEANC_4,MEANC_5,MEANC_6,MEANC_7)
%  Create fits.
%
%  Data for 'C=0' fit:
%      X Input : time
%      Y Output: meanC_1
%  Data for 'C=0.0625' fit:
%      X Input : time
%      Y Output: meanC_2
%  Data for 'C=0.125' fit:
%      X Input : time
%      Y Output: meanC_3
%  Data for 'C=0.25' fit:
%      X Input : time
%      Y Output: meanC_4
%  Data for 'C=0.5' fit:
%      X Input : time
%      Y Output: meanC_5
%  Data for 'C=1' fit:
%      X Input : time
%      Y Output: meanC_6
%  Data for 'C=2' fit:
%      X Input : time
%      Y Output: meanC_7
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Oct-2018 02:26:51

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 7, 1 );
gof = struct( 'sse', cell( 7, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'C=0'.
[xData, yData] = prepareCurveData( time, meanC_1 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.430207391329584 0.184816320124136 0.430207391329584 0.904880968679893 0.979748378356085 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0' );
plot( fitresult{1}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_1
grid on

%% Fit: 'C=0.0625'.
[xData, yData] = prepareCurveData( time, meanC_2 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.4 0.258064695912067 0.4 1 0.4 6];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.0625' );
plot( fitresult{2}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_2
grid on

%% Fit: 'C=0.125'.
[xData, yData] = prepareCurveData( time, meanC_3 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.602843089382083 0.711215780433683 0.22174673401724 0.22174673401724 0.117417650855806 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.125' );
plot( fitresult{3}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_3
grid on

%% Fit: 'C=0.25'.
[xData, yData] = prepareCurveData( time, meanC_4 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.318778301925882 0.424166759713807 0.085515797090044 0.507858284661118 0.085515797090044 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.25' );
plot( fitresult{4}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_4
grid on

%% Fit: 'C=0.5'.
[xData, yData] = prepareCurveData( time, meanC_5 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.801014622769739 0.0292202775621463 0.4886 0.928854139478045 0.730330862855453 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.5' );
h = plot( fitresult{5}, xData, yData, excludedPoints );
legend( h, 'meanC_5 vs. time', 'Excluded meanC_5 vs. time', 'C=0.5', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel meanC_5
grid on

%% Fit: 'C=1'.
[xData, yData] = prepareCurveData( time, meanC_6 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.578525061023439 0.237283579771521 0.07 0.458848828179931 0.963088539286913 5];

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=1' );
h = plot( fitresult{6}, xData, yData );
legend( h, 'meanC_6 vs. time', 'C=1', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel meanC_6
grid on

%% Fit: 'C=2'.
[xData, yData] = prepareCurveData( time, meanC_7 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', 1 );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.521135830804001 0.231594386708524 0.04 0.488897743920167 0.62406008817369 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{7}, gof(7)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=2' );
h = plot( fitresult{7}, xData, yData, excludedPoints );
legend( h, 'meanC_7 vs. time', 'Excluded meanC_7 vs. time', 'C=2', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel meanC_7
grid on


