function [fitresult, gof] = D_both(time, meanC_1, meanC_2, meanC_3, meanC_4, meanC_5, meanC_6, meanC_7)
%CREATEFITS1(TIME,MEANC_1,MEANC_2,MEANC_3,MEANC_4,MEANC_5,MEANC_6,MEANC_7)
%  Create fits.
%
%  Data for 'C=0' fit:
%      X Input : time
%      Y Output: meanC_1
%  Data for 'C=0.0625' fit:
%      X Input : time
%      Y Output: meanC_2
%  Data for 'C=0.125' fit:
%      X Input : time
%      Y Output: meanC_3
%  Data for 'C=0.25' fit:
%      X Input : time
%      Y Output: meanC_4
%  Data for 'C=0.5' fit:
%      X Input : time
%      Y Output: meanC_5
%  Data for 'C=1' fit:
%      X Input : time
%      Y Output: meanC_6
%  Data for 'C=2' fit:
%      X Input : time
%      Y Output: meanC_7
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Oct-2018 02:49:13

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 7, 1 );
gof = struct( 'sse', cell( 7, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'C=0'.
[xData, yData] = prepareCurveData( time, meanC_1 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.583185731454876 0.740032327987778 0.0781755287531837 0.234826914747904 0.734957541696052 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0' );
plot( fitresult{1}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_1
grid on

%% Fit: 'C=0.0625'.
[xData, yData] = prepareCurveData( time, meanC_2 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.866930291751916 0.0862345298634963 0 0.366436616319199 0.369198804330018 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.0625' );
plot( fitresult{2}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_2
grid on

%% Fit: 'C=0.125'.
[xData, yData] = prepareCurveData( time, meanC_3 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.597941635383889 0.789363943641905 0.431413827463545 0.367652918437877 0.206027859505195 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.125' );
plot( fitresult{3}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_3
grid on

%% Fit: 'C=0.25'.
[xData, yData] = prepareCurveData( time, meanC_4 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.771933917099107 0.20567452146476 0.4 0.388271631047802 0.551778531957227 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.25' );
plot( fitresult{4}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_4
grid on

%% Fit: 'C=0.5'.
[xData, yData] = prepareCurveData( time, meanC_5 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.641940620399187 0.48448037239818 0 0.151845525116267 0.781931966588002 5];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=0.5' );
plot( fitresult{5}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_5
grid on

%% Fit: 'C=1'.
[xData, yData] = prepareCurveData( time, meanC_6 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.294066333758628 0.8 0.183907788282417 0.530872257027928 0.0914987313394122 7];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=1' );
plot( fitresult{6}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_6
grid on

%% Fit: 'C=2'.
[xData, yData] = prepareCurveData( time, meanC_7 );

% Set up fittype and options.
ft = fittype( '(k1./(1 + (k1-n0)./n0*exp(-r1.*(x-xc))))*heaviside(xc-x) + (k2./(1 + (k2-n0)./n0*exp(-r2.*(x-xc))))*heaviside(x-xc)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', [36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62] );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0];
opts.StartPoint = [0.3 0.112283962156027 0.4 0.784427890743913 0.291570317906931 6];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{7}, gof(7)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'C=2' );
plot( fitresult{7}, xData, yData, excludedPoints );
% Label axes
xlabel time
ylabel meanC_7
grid on


